version: '3.8'

services:
  reverse-proxy:
    image: python:3.10
    container_name: reverse_proxy
    ports:
      - "7065:7065"
    working_dir: /reverse-proxy
    command: sh -c 'gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:7065 app:app'
    build:
      context: .